#!/bin/bash

source ./common

title 'Coordinator test.'

if ! [ -x "$(command -v jq)" ]; then
  echo 'Error: jq is not installed.' >&2
  exit 1
fi

# XXX: For the final version, this should be "chainlink", not cldev.
agreement_response=$(cldev -j agreements create  $SRCROOT/integration/agreement.json)
