#!/bin/bash

source ./common

title 'Coordinator test.'

if ! [ -x "$(command -v jq)" ]; then
  echo 'Error: jq is not installed.' >&2
  exit 1
fi

agreement_response=$(chainlink -j agreements create  $SRCROOT/integration/agreement.json)
